hrportal/client/src/components/SignupForm.module.css
hrportal/client/src/components/ViewCandidateDetail.js

resolved issue related to file download and signup screen

resolved issue related to file download and signup screen

---

hrportal/client/src/components/Status.js
hrportal/client/src/components/Status.module.css
hrportal/server/src/controllers/statusController.js

Hiring Portal Phase 2 status screen integration with backend final

Phase2 front end admin skill set

---

hrportal/client/src/components/SkillSets.js
hrportal/server/server.js
hrportal/server/server_error.log
hrportal/server/server_info.log
hrportal/server/src/controllers/skillsSetsController.js
hrportal/server/src/routes/skillsSetRoutes.js

skillset screen route"/onLoadSkillset" ,'/addskillset', '/editskillset/:id' are completed

Phase2 frontend skillset integration

---

hrportal/server/src/controllers/statusController.js
hrportal/server/src/utility/insertSkillData.js
hrportal/server/src/utility/skillsConstants.js

I have modified some skillsets,
Please ask DEV team to drop the existing skillset and subskillset collection and run the server code again.
Thank you.

Bug: Minor changes in populating skillset

---

hrportal/client/src/components/SkillSets.module.css
hrportal/client/src/components/Status.js
hrportal/client/src/components/Status.module.css
hrportal/client/src/hooks/useStatus.js

I was Working on Status Screen Validation so for that updated the following code base:
1) Created HOOK useStatus.js file
2) Updated Status.js and Status.module.css code

Phase2 frontend status validation

---

hrportal/server/src/controllers/skillsSetsController.js
hrportal/server/src/controllers/statusController.js
hrportal/server/src/routes/skillsSetRoutes.js

1. Corrected some edge cases present in the code.
2.  Implemented search functionality

Bugfix skillsets

---

hrportal/client/src/components/EditCandidateDetails.js
hrportal/client/src/components/Navbar.js
hrportal/client/src/components/NewCandidate.js
hrportal/client/src/components/NewCandidate.module.css
hrportal/client/src/components/ViewCandidateDetail.js
hrportal/client/src/context/AuthContext.js
hrportal/server/src/controllers/userController.js

Admin role configuration completed

Hiring Portal Phase 2 admin role

---

hrportal/client/src/App.js
hrportal/client/src/components/Layout.js
hrportal/client/src/components/PeriodicalDashboard.js
hrportal/client/src/components/PeriodicalDashboard.module.css
hrportal/client/src/hooks/usePeriodicDashboard.js
hrportal/server/src/controllers/dashboardController.js

This branch includes only integration code which will have 
Hook: usePeriodicDashboard.js
Component: PeriodicDashboard.js, PeriodicDashboard.module.css
Note: CSS AND NAVBAR implementation we will do in new branch

 Periodic dashboard Integration

---

hrportal/client/src/components/PeriodicalDashboard.js

Phase 2 sprint 4 feedback for periodic dashboard in which i resolved to issues which are following                                                            
- remove the subskill column if value is zero in every cell.
- when we select different main skill in dropdown of periodic dashboard then all subskill are rendering in table.

Hiring Portal Phase 2 sprint 4 feedback for periodic dashboard

---

hrportal/client/src/hooks/useJoiningDashboard.js

1. Created hooks for joining dashboard.

Feature- Joining Dashboard - Integration

---

hrportal/server/src/controllers/dashboardController.js
hrportal/server/src/routes/dashboardRoutes.js

1. Completed deferred dashboard
2.  Configured skillset filter for joining dashboard
3. Wrote validation check for dates for all the dashboards.

Feature- Deferred dashboard

---

hrportal/client/src/components/DeferredDashboard.module.css
hrportal/client/src/components/InterviewDashboard.module.css
hrportal/client/src/components/JoiningDashboard.module.css
hrportal/client/src/components/Navbar.js
hrportal/client/src/components/PeriodicalDashboard.module.css
hrportal/server/server_info.log

css updates for all dashboard

---

hrportal/client/src/components/Navbar.js
hrportal/server/server_info.log

corrected links for dashboard

---

hrportal/client/src/components/CellWithTooltip.js
hrportal/client/src/components/CellWithTooltip.module.css
hrportal/client/src/components/EditCandidateDetails.js
hrportal/client/src/components/InterviewDashboard.js
hrportal/client/src/components/InterviewDashboard.module.css
hrportal/client/src/components/NewCandidate.js
hrportal/server/server_info.log

added tooltip when user hover hover on cell in interview dashboard

Phase2 frontend hover

---

hrportal/client/src/components/DeferredDashboard.js
hrportal/client/src/components/DeferredDashboard.module.css
hrportal/client/src/components/InterviewDashboard.module.css
hrportal/client/src/components/JoiningDashboard.js
hrportal/client/src/components/JoiningDashboard.module.css
hrportal/client/src/components/Navbar.js
hrportal/client/src/components/PeriodicalDashboard.module.css
hrportal/client/src/hooks/useDeferredDashboard.js
hrportal/server/server_info.log
hrportal/server/src/controllers/dashboardController.js

resolved the issues raised on 12/9/2024

Hiring Portal Phase 2  resolved the issues raised on 12/9/2024

---

hrportal/client/package-lock.json
hrportal/client/package.json
hrportal/client/src/components/EditCandidateDetails.js
hrportal/client/src/components/JoiningDashboard.js
hrportal/client/src/components/Navbar.js
hrportal/client/src/components/NewCandidate.js
hrportal/client/src/components/ViewCandidateDetail.js
hrportal/client/src/components/ViewCandidateDetail.module.css
hrportal/client/src/components/ViewSearchCandidatePage.module.css

Hiring Portal Phase 2  resolved the issues raised on 13/9/2024

---

hrportal/client/package-lock.json
hrportal/client/package.json
hrportal/client/src/components/DeferredDashboard.js
hrportal/client/src/components/DeferredDashboard.module.css
hrportal/client/src/components/DownloadExcelReport.js
hrportal/client/src/components/DownloadExcelReport.module.css
hrportal/client/src/components/InterviewDashboard.js
hrportal/client/src/components/InterviewDashboard.module.css
hrportal/client/src/components/JoiningDashboard.js
hrportal/client/src/components/JoiningDashboard.module.css
hrportal/client/src/components/PeriodicalDashboard.js
hrportal/client/src/components/PeriodicalDashboard.module.css

Hiring Portal Phase 2  download report

---

hrportal/client/src/components/DeferredDashboard.js
hrportal/client/src/components/InterviewDashboard.js
hrportal/client/src/components/JoiningDashboard.js
hrportal/client/src/components/PeriodicalDashboard.js
hrportal/client/src/components/SkillSets.js

Download report issues resolved.

Phase2 frontend UI errors

---

hrportal/client/src/components/DeferredDashboard.module.css
hrportal/client/src/components/SkillSets.js
hrportal/server/server_info.log

fixed few minor UI issues

---

hrportal/client/src/components/InterviewDashboard.js
hrportal/client/src/components/JoiningDashboard.js
hrportal/client/src/components/PeriodicalDashboard.js

Hiring Portal Phase 2  fixed issues
